# Generated by Django 3.0.5 on 2020-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fqd_name', models.CharField(max_length=255)),
                ('blocked', models.BooleanField(default=False)),
                ('original_ip', models.CharField(max_length=15)),
                ('is_threat', models.BooleanField(default=False)),
                ('last_accessed', models.TimeField()),
            ],
        ),
    ]
