# Generated by Django 3.0.5 on 2020-04-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_add_threat_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='last_accessed',
        ),
    ]
