# Generated by Django 3.0.5 on 2020-04-19 21:29

from django.db import migrations, models
import rest.enum_classes


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20200419_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(choices=[(rest.enum_classes.ThreatType['HOST'], 'HOST'), (rest.enum_classes.ThreatType['FILE'], 'FILE'), (rest.enum_classes.ThreatType['USER_DEFINED'], 'USER_DEFINED')], max_length=20, unique=True),
        ),
    ]
