# Generated by Django 3.0.5 on 2020-04-28 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_choices_names_on_threat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.FloatField(help_text='average packets per minute')),
                ('last_accessed', models.DateTimeField(help_text='when HOST has been accessed recently, meaning there was net traffic with this host')),
                ('host_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Host')),
            ],
        ),
    ]
