# Generated by Django 3.0.5 on 2020-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_create_stats_add_created_on_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='ppm',
            field=models.FloatField(help_text='average packets per minute, may be empty', null=True),
        ),
    ]
