# Generated by Django 3.0.5 on 2020-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_null_on_ppm_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='host_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.Host'),
        ),
    ]
